'use strict';
module.exports = () => {
    let department = [{"id": 1, "name": "Aeronautical Engineering", "abbreviated_name": "AUE", "status": "t","course_id":1},
    {"id": 2, "name": "Automobile Engineering", "abbreviated_name": "ATE", "status": "t","course_id":1},
    {"id": 3, "name": "Bio Medical Engineering", "abbreviated_name": "BME", "status": "t","course_id":1},
    {"id": 4, "name": "Bio Technology", "abbreviated_name": "BT", "status": "t","course_id":1},
    {"id": 5, "name": "Chemical Engineering", "abbreviated_name": "CE", "status": "t","course_id":1},
    {"id": 6, "name": "Civil Engineering", "abbreviated_name": "CVE", "status": "t","course_id":1},
    {"id": 7, "name": "Computer Engineering", "abbreviated_name": "CSE", "status": "t","course_id":1},
    {"id": 8, "name": "Electrical & Electronics Engineering", "abbreviated_name": "ECE", "status": "t","course_id":1},
    {"id": 9, "name": "Electrical Engineering", "abbreviated_name": "EEE", "status": "t","course_id":1},
    {"id": 10, "name": "Electronics Engineering", "abbreviated_name": "ELE", "status": "t","course_id":1},
    {"id": 11, "name": "Electronics & Communication Engineering", "abbreviated_name": "ECCE", "status": "t","course_id":1},
    {"id": 12, "name": "Environmental Engineering", "abbreviated_name": "ENVE", "status": "t","course_id":1},
    {"id": 13, "name": "Food Processing Technology", "abbreviated_name": "FPT", "status": "t","course_id":1},
    {"id": 14, "name": "Industrial Engineering", "abbreviated_name": "IE", "status": "t","course_id":1},
    {"id": 15, "name": "Information Technology", "abbreviated_name": "IT", "status": "t","course_id":1},
    {"id": 16, "name": "Instrumentation & Control Engineering", "abbreviated_name": "ICE", "status": "t","course_id":1},
    {"id": 17, "name": "Mechanical Engineering", "abbreviated_name": "ME", "status": "t","course_id":1},
    {"id": 18, "name": "Mechatronics Engineering", "abbreviated_name": "MTE", "status": "t","course_id":1},
    {"id": 19, "name": "Metallurgy Engineering", "abbreviated_name": "MUE", "status": "t","course_id":1},
    {"id": 20, "name": "Mining Engineering", "abbreviated_name": "MIE", "status": "t","course_id":1},
    {"id": 21, "name": "Plastic Technology", "abbreviated_name": "PT", "status": "t","course_id":1},
    {"id": 22, "name": "Power electronics", "abbreviated_name": "POE", "status": "t","course_id":1},
    {"id": 23, "name": "Production Engineering", "abbreviated_name": "PRE", "status": "t","course_id":1},
    {"id": 24, "name": "Rubber Technology", "abbreviated_name": "RT", "status": "t","course_id":1},
    {"id": 25, "name": "Textile Processing", "abbreviated_name": "TP", "status": "t","course_id":1},
    {"id": 26, "name": "Textile Technology", "abbreviated_name": "TT", "status": "t","course_id":1},
    {"id": 27, "name": "Information & Communication Technology", "abbreviated_name": "ICT", "status": "t","course_id":1},
    {"id": 28, "name": "Manufacturing Engineering", "abbreviated_name": "MFT", "status": "t","course_id":1},
    {"id": 29, "name": "Environmental Science & Technology", "abbreviated_name": "EST", "status": "t","course_id":1},
    {"id": 30, "name": "Chemical Technology", "abbreviated_name": "CT", "status": "t","course_id":1},
    {"id": 31, "name": "All", "abbreviated_name": "A", "status": "t","course_id":1}]
	return department;
}