//login section
export const LOGIN= 'LOGIN';
export const CHECK_IS_LOGIN= 'CHECK_IS_LOGIN';
export const LOGOUT= 'LOGOUT';
export const GET_ALL_DEPARTMENT_FOR_COURSE= 'GET_ALL_DEPARTMENT_FOR_COURSE';
export const ADD_DEPARTMENT= 'ADD_DEPARTMENT';
export const DELETE_DEPARTMENT= 'DELETE_DEPARTMENT';
export const EDIT_DEPARTMENT= 'EDIT_DEPARTMENT';
export const HIDE_SLACKBAR= 'HIDE_SLACKBAR';
export const CHANGE_SLACKBAR_MSG= 'CHANGE_SLACKBAR_MSG';
export const HANDLE_TAB_CHANGE= 'HANDLE_TAB_CHANGE';
export const PAGE_CHANGE= 'PAGE_CHANGE';
export const GET_ALL_CURRICULUM_FOR_COURSE= 'GET_ALL_CURRICULUM_FOR_COURSE';
export const ADD_CURRICULUM= 'ADD_CURRICULUM';
export const DELETE_CURRICULUM= 'DELETE_CURRICULUM';
export const EDIT_CURRICULUM= 'EDIT_CURRICULUM';
export const ADD_STUDENT = 'ADD_STUDENT';
export const EDIT_STUDENT = 'EDIT_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const STUDENT_LIST = 'STUDENT_LIST'

export const ADD_TEACHER = 'ADD_TEACHER';
export const EDIT_TEACHER = 'EDIT_TEACHER';
export const DELETE_TEACHER = 'DELETE_TEACHER';
export const TEACHER_LIST = 'TEACHER_LIST'

export const ADD_SUBJECT = 'ADD_SUBJECT';
export const EDIT_SUBJECT = 'EDIT_SUBJECT';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const SUBJECT_LIST = 'SUBJECT_LIST'

export const ADD_EVENT = 'ADD_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const EVENT_LIST = 'EVENT_LIST'
